version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERL: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./accounts/db/init.sql:/docker-entrypoint-initdb.d/init-accounts.sql
    ports:
      - 5432:5432

